# Generated by Django 5.0.6 on 2024-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_id', models.CharField(max_length=32, verbose_name='会议ID')),
                ('audio_id', models.CharField(max_length=64, verbose_name='音频ID')),
                ('user_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='工号')),
                ('model', models.CharField(default='NISQAv2', max_length=16, verbose_name='模型')),
                ('mos', models.FloatField(blank=True, null=True, verbose_name='主观评分')),
                ('noi', models.FloatField(blank=True, null=True, verbose_name='噪声评分')),
                ('dis', models.FloatField(blank=True, null=True, verbose_name='连续评分')),
                ('col', models.FloatField(blank=True, null=True, verbose_name='失真评分')),
                ('loud', models.FloatField(blank=True, null=True, verbose_name='响度评分')),
            ],
            options={
                'verbose_name': '音频评分',
                'verbose_name_plural': '音频评分',
            },
        ),
    ]
